PWX-19006: Do not set pxd_bd_ops.submit_bio, 5.10 kernel uses this to…
portworx/px-fuse pull request #196
Opened 2021-03-06 05:40 UTC by prabirpaul

… submit ios to pxd instead of the request queue.

On 5.10 kernel, the request queue is bypassed if submit_bio is set for the pxd block device. Our internal mmap request queue depends on request queue based processing. Even if we can reroute to slowpath it's an extra cost which can be avoided. 
It's not needed and compilation works fine on both 5.9 and 5.10.

2021-03-07 13:12 UTC, sulakshm requested changes
Yes, requeue queueing is bypassed if submit_bio handler is set.

```Our internal mmap request queue depends on request queue based processing.``` ===> This is incorrect.

The reason it fails is, data exchange from kernel to userspace is good, but unexpected to happen through make request interface for a native path device. But the data exchange from userspace to kernel ends up completing IO  as a request queue completion, thus failing. The posted fix will fail fastpath devices.
And since now submit_bio is part of  block device handlers methods which are static, we need two instances of it to set appropriately.


Proposed fix:
Branch: ln/PWX-19006 (based on 2.7.0)
device add, del, resize works in native path.
for fastpath seems online resize is broken, we can revisit this outside.

```
diff --git a/io.c b/io.c
index 4fa9a09..1b572c8 100644
--- a/io.c
+++ b/io.c
@@ -1100,7 +1100,7 @@ static int io_discard(struct io_kiocb *req, const struct sqe_submit *s,

        inode = req->file->f_inode;
        if (S_ISBLK(inode->i_mode)) {
-               struct block_device *bdev = inode->i_bdev;
+               struct block_device *bdev = I_BDEV(inode);
                struct address_space *mapping = bdev->bd_inode->i_mapping;
                truncate_inode_pages_range(mapping, off, off + bytes - 1);
                ret = blkdev_issue_discard(bdev, off / SECTOR_SIZE,
diff --git a/pxd.c b/pxd.c
index b4be22b..dc11eff 100644
--- a/pxd.c
+++ b/pxd.c
@@ -379,6 +379,12 @@ static const struct block_device_operations pxd_bd_ops = {
        .owner                  = THIS_MODULE,
        .open                   = pxd_open,
        .release                = pxd_release,
+};
+
+static const struct block_device_operations pxd_bd_fp_ops = {
+       .owner                  = THIS_MODULE,
+       .open                   = pxd_open,
+       .release                = pxd_release,
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,9,0)
        .submit_bio             = pxd_make_request_fastpath,
 #endif
@@ -388,7 +394,11 @@ static void pxd_update_stats(struct fuse_req *req, int rw, unsigned int count)
 {
                struct pxd_device *pxd_dev = req->queue->queuedata;

-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0) || defined(__EL8__)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,11,0) || defined(__EL8__)
+               part_stat_lock();
+               part_stat_inc(pxd_dev->disk->part0, ios[rw]);
+               part_stat_add(pxd_dev->disk->part0, sectors[rw], count);
+#elif LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0) || defined(__EL8__)
                part_stat_lock();
                part_stat_inc(&pxd_dev->disk->part0, ios[rw]);
                part_stat_add(&pxd_dev->disk->part0, sectors[rw], count);
@@ -1046,11 +1056,11 @@ static blk_status_t pxd_queue_rq(struct blk_mq_hw_ctx *hctx,
        if (BLK_RQ_IS_PASSTHROUGH(rq) || !READ_ONCE(fc->allow_disconnected))
                return BLK_STS_IOERR;

-       pxd_printk("%s: dev m %d g %lld %s at %ld len %d bytes %d pages "
+       pxd_printk("%s: dev m %d g %lld %s at %lld len %d bytes %d pages "
                   "flags  %x\n", __func__,
                pxd_dev->minor, pxd_dev->dev_id,
                rq_data_dir(rq) == WRITE ? "wr" : "rd",
-               blk_rq_pos(rq) * SECTOR_SIZE, blk_rq_bytes(rq),
+               (unsigned long long)(blk_rq_pos(rq) * SECTOR_SIZE), blk_rq_bytes(rq),
                rq->nr_phys_segments, rq->cmd_flags);

        fuse_request_init(req);
@@ -1093,7 +1103,6 @@ static int pxd_init_disk(struct pxd_device *pxd_dev, struct pxd_add_ext_out *add
        disk->major = pxd_dev->major;
        disk->first_minor = pxd_dev->minor;
        disk->flags |= GENHD_FL_EXT_DEVT | GENHD_FL_NO_PART_SCAN;
-       disk->fops = &pxd_bd_ops;
        disk->private_data = pxd_dev;

        // only fastpath uses direct block io process bypassing request queuing
@@ -1105,6 +1114,7 @@ static int pxd_init_disk(struct pxd_device *pxd_dev, struct pxd_add_ext_out *add
 #else
        if (!pxd_dev->using_blkque) {
                pxd_printk("adding disk for fastpath device %llu", pxd_dev->dev_id);
+               disk->fops = &pxd_bd_fp_ops;
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,9,0)
          q = blk_alloc_queue(NUMA_NO_NODE);
 #elif LINUX_VERSION_CODE >= KERNEL_VERSION(5,7,0)
@@ -1129,6 +1139,7 @@ static int pxd_init_disk(struct pxd_device *pxd_dev, struct pxd_add_ext_out *add
        } else {
 #endif

+         disk->fops = &pxd_bd_ops;
 #ifdef __PX_BLKMQ__
          memset(&pxd_dev->tag_set, 0, sizeof(pxd_dev->tag_set));
          pxd_dev->tag_set.ops = &pxd_mq_ops;
@@ -1453,7 +1464,27 @@ ssize_t pxd_ioc_update_size(struct fuse_conn *fc, struct pxd_update_size *update
        set_capacity(pxd_dev->disk, update_size->size / SECTOR_SIZE);
        spin_unlock(&pxd_dev->lock);

-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,10,0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,11,0)
+{
+       // open code here, as interface unexported
+       loff_t disk_size, bdev_size;
+       struct block_device *bdev = pxd_dev->disk->part0;
+
+       if (!bdev) goto skipout;
+       spin_lock(&bdev->bd_size_lock);
+       disk_size = (loff_t) get_capacity(pxd_dev->disk) << 9;
+       bdev_size = i_size_read(bdev->bd_inode);
+       // we never allow shrinking
+       if (disk_size != bdev_size) {
+               printk(KERN_INFO
+                      "%s: detected capacity change from %lld to %lld\n",
+                      pxd_dev->disk->disk_name, bdev_size, disk_size);
+               i_size_write(bdev->bd_inode, disk_size);
+       }
+       spin_unlock(&bdev->bd_size_lock);
+}
+skipout:
+#elif LINUX_VERSION_CODE >= KERNEL_VERSION(5,10,0)
        revalidate_disk_size(pxd_dev->disk, true);
 #else
        err = revalidate_disk(pxd_dev->disk);
```

Test logs:
```
[root@centos8 px-fuse]# uname -r
5.11.3-1.el8.elrepo.x86_64
[root@centos8 px-fuse]# pxctl status
Status: PX is operational
License: Trial (expires in 31 days)
Node ID: c9558236-d38b-4eb1-8ba9-35da192b2c6b
        IP: 10.0.2.15
        Local Storage Pool: 1 pool
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE          USED    STATUS  ZONE    REGION
        0       HIGH            raid0           10.0 GiB        59 MiB  Online  default default
        Local Storage Devices: 1 device
        Device  Path            Media Type              Size            Last-Scan
        0:0     /dev/sdb        STORAGE_MEDIUM_MAGNETIC 10 GiB          07 Mar 21 07:44 EST
        total                   -                       10 GiB
        Cache Devices:
         * No cache devices
Cluster Summary
        Cluster ID: test1
        Cluster UUID: 2178e1e7-7198-4fbc-afa4-5272526a3fca
        Scheduler: none
        Nodes: 1 node(s) with storage (1 online)
        IP              ID                                      SchedulerNodeName       StorageNode     Used    Capacity        Status  StorageStatus   Version         Kernel                       OS
        10.0.2.15       c9558236-d38b-4eb1-8ba9-35da192b2c6b    N/A                     Yes             59 MiB  10.0 GiB        Online  Up (This node)  2.7.0.0-c57477c 5.11.3-1.el8.elrepo.x86_64   CentOS Linux 8
        Warnings:
                 WARNING: Swap is enabled on this node.
                 WARNING: Persistent journald logging is not enabled on this node.
Global Storage Pool
        Total Used      :  59 MiB
        Total Capacity  :  10.0 GiB
[root@centos8 px-fuse]# pxctl v l
ID                      NAME    SIZE    HA      SHARED  ENCRYPTED       PROXY-VOLUME    IO_PRIORITY     STATUS                          SNAP-ENABLED
1134501858203270223     native  1 GiB   1       no      no              no              HIGH            down - attached on 10.0.2.15    no
1002237680776062676     vol1    1 GiB   1       no      no              no              HIGH            up - detached                   no
[root@centos8 px-fuse]# pxctl v d -f native
Volume native successfully deleted.
[root@centos8 px-fuse]# pxctl v c native
Volume successfully [...]

2021-03-07 19:22 UTC, prabirpaul commented
Our internal mmap request queue depends on request queue based processing. ===> This is incorrect.

It's true for nativepath. Any change to it is a fastpath requirement. This bug is a regression from supporting the new interface on >5.9 kernel, which is a fastpath only requirement. Given that fastpath is not shipping in 2.7.0, this PR is to make nativepath work and nothing more.

Any fastpath related changes should go to master only, we can bring them to 2.7 post GA.

2021-03-08 02:53 UTC, sulakshm commented
> Our internal mmap request queue depends on request queue based processing. ===> This is incorrect.
> 
> It's true for nativepath. Any change to it is a fastpath requirement. This bug is a regression from supporting the new interface on >5.9 kernel, which is a fastpath only requirement. Given that fastpath is not shipping in 2.7.0, this PR is to make nativepath work and nothing more.
> 
> Any fastpath related changes should go to master only, we can bring them to 2.7 post GA.

Prabir, I have already posted the needed changes to support it and not break it.

2021-03-08 03:32 UTC, sulakshm approved these changes
based on offline discussion, approving the posted changes with the disclaimer that fastpath will be broken in those kernels from 5.10. Failure will be a crash in IO path because fastpath volume IO are not expected in userspace but fuse driver will anyways send it to userspace.

Also, master branch has been broken (for px-fuse submodule since last december pointing to a private branch). So all these changes are tested only on a feature branch, so the earlier we get these in, the better it is.

2021-03-08 04:41 UTC, sulakshm commented
Also remember px-fuse compilation will fail in 5.11 kernel

2021-03-08 07:00 UTC, prabirpaul commented
Ok got it. I think we can release note that 5.11 isn't supported yet. Once 2.7.0 goes out we will have some breathing room to incorporate/validate the submit_bio related changes. Will check with Ben/Prashant tomorrow.

2021-03-08 07:08 UTC, merged